name: wikiwho-demo-environment
channels:
  - conda-forge
dependencies:
  - python=>3.6
  - appmode
  - numpy
  - pandas
  - pip:
    - wordcloud
    - nbstripout
    - wikiwho_wrapper
    - jupyter
    - ipywidgets
    - matplotlib
    - plotly
    - qgrid
    - nbstripout
    - multidict