name: wikiwho-demo-environment
channels:
  - conda-forge
dependencies:
  - python=>3.6
  - appmode
  - numpy
  - pandas
  - jupyter
  - plotly
  - qgrid
  - nbstripout
  - matplotlib
  - pip:
    - wordcloud
    - nbstripout
    - wikiwho_wrapper
